name: Test for all containers

on:
  push:
    branches: [ "refactor" ]
  pull_request:
    branches: [ "refactor" ]

env:
  BUILD_TYPE: Debug

jobs:
  test:
    name: HMFOCX- ${{matrix.CONTAINER}} -TEST
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CONTAINER: [LIST, MAP, POOL, STACK, QUEUE, HEAP, SET, ARR, STR]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: |
          cmake  \
          -B ${{github.workspace}}/bin -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=gcc  \
          -DHMFOCX_BUILD_TEST=ON -DHMFOCX_${{matrix.CONTAINER}}_TEST=ON 

    - name: Build
      run: |
        CONTAINER="${{matrix.CONTAINER}}" container="${CONTAINER,,}"
        cmake  \
        --build ${{github.workspace}}/bin  \
        --target test_hm_${container} --config ${{env.BUILD_TYPE}}

    - name: Test [ ${{matrix.CONTAINER}} ]
      working-directory: ${{github.workspace}}/bin
      run: |
          CONTAINER="${{matrix.CONTAINER}}" container="${CONTAINER,,}"
          ctest  \
          -C ${{env.BUILD_TYPE}} \
          -R "^test_hm_${container}$" -V